app = "backend-twilight-tree-2764"
primary_region = "bom"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  DB_HOST = "turf-db-monish.internal"
  DB_USER = "postgres"
  DB_NAME = "turfbooking"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "10s"
    interval = "15s"
    timeout = "2s"
